# Generated by Django 5.0.4 on 2024-04-22 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='university',
        ),
        migrations.RemoveField(
            model_name='student',
            name='enrollment_number',
        ),
    ]
